apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: todo
  name: todo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: todo
    spec:
      containers:
      - image: angelobelchior/todo
        name: todo
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
